name: Go

on:
  push:
    branches: [ "main" ]
    paths:
      - "go.mod"
      - "go.sum"
      - "**.go"
  pull_request:
    branches: [ "main" ]
    paths:
      - "go.mod"
      - "go.sum"
      - "**.go"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v

    - name: Test
      run: DEVELBOX_DEBUG=1 go test -v ./...

    # Cache dependencies and build artifacts
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-